version: '3.5'

services:
  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3.7.17-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbitmq

networks:
  rabbitmq:
    external:
      name: rabbitmq
