version: '3.7'

services:
  rabbit:
    container_name: rabbitmq
    image: carlonicora/rabbitmq:3.8.1-alpine
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
    name: phlow
